services:
  # Our postgres database
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: nosemueve 
    restart: always
    ports:
      - "5432:5432"

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin 
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: 
      - start-dev
      - --db=dev-file
volumes:
  keycloak-data:
    driver: local